apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: for-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCQzfdM8BPlDMezY03KVIH+WLW/NwPjjZxWy3He8JLgOhWzIaeFXqn1oKS7M6IuWL99Bkold57/8SYpbEwX+yFSXJPKa/WgJ8uYsi2l9DnzyC1vxq/lV/JQKVoHIIZHDnT+Ic4e5X65AI7sAGqlzu/UJBKPMoYTEYilfxFGnrp07OgfrMyrm6Gt/PC4jtbm20lg7a/PtMvdWTkVP0vFQFBj1LCD/SOU528MydJROgQ0LtbVNbLDkp+Phmp5z89fO7FlSHN6x8yBsEqHFJ5XKvy017bb0lU4+qg6cchHZMlaJzk/82HpIZloficzfyBjy6h/ypp3eKCvKk4rmKTVnoBqIY338l1JI5S2+4HusBwTwm+NQhn924MMGpY7poJaq/c0+Ai9twIJwQRRBEJXAZmDKRnlFwGHQPM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: for-sync
      namespace: default

