apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: eg-8
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      rafay.dev/clusterID: 4qkolkn
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        description: Patching
        name: action1
        patchConfig:
        - op: replace
          path: .spec.config.spec.nodePools[0].properties.minCount
          value: 1
        type: patch
      name: op1
    - action:
        description: Patching
        name: action2
        patchConfig:
        - op: replace
          path: .spec.config.spec.nodePools[0].properties.count
          value: 2
        type: patch
      name: op2
status:
  jobStatus:
    lastUpdated: "2023-06-20T17:13:43Z"
    reason: workflow run cancelled
    status: cancelled
  resourcesStatus:
  - name: jai-eks-2
    operations:
    - action:
        description: Patching
        lastUpdated: "2023-06-20T17:13:43Z"
        name: action1
        reason: 'activity failed: defaultproject-jai-eks-2-action1: Could not apply
          patch replace operation does not apply: doc is missing path: /spec/config/spec/nodePools/0/properties/minCount:
          missing value'
        status: fail
    - action:
        description: Patching
        lastUpdated: "2023-06-20T17:13:43Z"
        name: action2
        reason: workflow run cancelled
        status: cancelled
    project: defaultproject
