apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: eg-9
  project: defaultproject
spec:
  agents:
  - name: engine-agent
  fleet:
    kind: clusters
    labels:
      fruit: banana
      veg: tomato
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        description: Patching
        patchConfig:
        - op: replace
          path: .spec.config.spec.nodePools[0].properties.count
          value: 2
        type: patch
      prehooks:
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner: cluster
        description: List all pods
        inject:
        - KUBECONFIG
status:
  jobStatus:
    lastUpdated: "2023-05-02T16:38:32Z"
    reason: 'activity pending: 1-prehook-1-218: '
    status: skipped
  resourcesStatus:
  - name: aws-1
    operations:
    - action:
        description: Patching
        lastUpdated: "2023-05-02T08:56:39Z"
        status: waiting
      prehooks:
      - description: List all pods
        lastUpdated: "2023-05-02T08:56:39Z"
        status: pending
    project: defaultproject
