apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: fp1
  project: defaultproject
spec:
  agents:
  - name: kalyan-docker
  fleet:
    kind: clusters
    labels:
      role: qa
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        controlPlaneUpgradeConfig:
          version: 1.24.10
        description: upgrading control plane A
        name: action1
        nodeGroupsAndControlPlaneUpgradeConfig: {}
        nodeGroupsUpgradeConfig: {}
        type: controlPlaneUpgrade
      name: op1
      prehooks:
      - containerConfig:
          arguments:
          - get
          - po
          image: bitnami/kubectl
          runner: cluster
        description: list all pods 10
        httpConfig: {}
        inject:
        - KUBECONFIG
        name: prehooks1
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner: cluster
        description: list all pods 2
        httpConfig: {}
        inject:
        - KUBECONFIG
        name: prehooks2
    - action:
        controlPlaneUpgradeConfig: {}
        description: upgrading control plane and nodegroup
        name: action2
        nodeGroupsAndControlPlaneUpgradeConfig: {}
        nodeGroupsUpgradeConfig:
          names:
          - ng1
          - ng2
          version: 1.24.10
        type: nodeGroupsUpgrade
      name: op2
      posthooks:
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner: cluster
        description: list all pods 1
        httpConfig: {}
        inject:
        - KUBECONFIG
        name: posthooks1
status:
  jobStatus:
    lastUpdated: "2023-07-13T10:57:39Z"
    reason: |-
      7 problems:

      - activity failed: defaultproject-dtyhfgf-prehooks1: timeout waiting for agent to ack
      - activity failed: defaultproject-some-prehooks1: timeout waiting for agent to ack
      - activity failed: defaultproject-del-cluster-3-prehooks1: timeout waiting for agent to ack
      - activity failed: defaultproject-fghjk-prehooks1: timeout waiting for agent to ack
      - activity failed: defaultproject-testeks1-prehooks1: timeout waiting for agent to ack
      - activity failed: defaultproject-sftdhgf-prehooks1: timeout waiting for agent to ack
      - activity failed: defaultproject-swag-eks-prehooks1: timeout waiting for agent to ack
    status: completed_with_failures
  resourcesStatus:
  - name: del-cluster-3
    operations:
    - action:
        description: upgrading control plane
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action1
        status: waiting
      prehooks:
      - description: list all pods 10
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks1
        reason: timeout waiting for agent to ack
        status: fail
      - description: list all pods 2
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks2
        status: waiting
    - action:
        description: upgrading control plane and nodegroup
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action2
        status: waiting
      posthooks:
      - description: list all pods 1
        lastUpdated: "2023-07-13T10:57:39Z"
        name: posthooks1
        status: waiting
    - action:
        description: upgrading control plane
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action1
        status: waiting
      prehooks:
      - description: list all pods 10
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks1
        reason: timeout waiting for agent to ack
        status: fail
      - description: list all pods 2
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks2
        status: waiting
    - action:
        description: upgrading control plane and nodegroup
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action2
        status: waiting
      posthooks:
      - description: list all pods 1
        lastUpdated: "2023-07-13T10:57:39Z"
        name: posthooks1
        status: waiting
    - action:
        description: upgrading control plane
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action1
        status: waiting
      prehooks:
      - description: list all pods 10
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks1
        reason: timeout waiting for agent to ack
        status: fail
      - description: list all pods 2
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks2
        status: waiting
    - action:
        description: upgrading control plane and nodegroup
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action2
        status: waiting
      posthooks:
      - description: list all pods 1
        lastUpdated: "2023-07-13T10:57:39Z"
        name: posthooks1
        status: waiting
    - action:
        description: upgrading control plane
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action1
        status: waiting
      prehooks:
      - description: list all pods 10
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks1
        reason: timeout waiting for agent to ack
        status: fail
      - description: list all pods 2
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks2
        status: waiting
    - action:
        description: upgrading control plane and nodegroup
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action2
        status: waiting
      posthooks:
      - description: list all pods 1
        lastUpdated: "2023-07-13T10:57:39Z"
        name: posthooks1
        status: waiting
    - action:
        description: upgrading control plane
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action1
        status: waiting
      prehooks:
      - description: list all pods 10
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks1
        reason: timeout waiting for agent to ack
        status: fail
      - description: list all pods 2
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks2
        status: waiting
    - action:
        description: upgrading control plane and nodegroup
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action2
        status: waiting
      posthooks:
      - description: list all pods 1
        lastUpdated: "2023-07-13T10:57:39Z"
        name: posthooks1
        status: waiting
    - action:
        description: upgrading control plane
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action1
        status: waiting
      prehooks:
      - description: list all pods 10
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks1
        reason: timeout waiting for agent to ack
        status: fail
      - description: list all pods 2
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks2
        status: waiting
    - action:
        description: upgrading control plane and nodegroup
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action2
        status: waiting
      posthooks:
      - description: list all pods 1
        lastUpdated: "2023-07-13T10:57:39Z"
        name: posthooks1
        status: waiting
    - action:
        description: upgrading control plane
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action1
        status: waiting
      prehooks:
      - description: list all pods 10
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks1
        reason: timeout waiting for agent to ack
        status: fail
      - description: list all pods 2
        lastUpdated: "2023-07-13T10:57:39Z"
        name: prehooks2
        status: waiting
    - action:
        description: upgrading control plane and nodegroup
        lastUpdated: "2023-07-13T10:57:39Z"
        name: action2
        status: waiting
      posthooks:
      - description: list all pods 1
        lastUpdated: "2023-07-13T10:57:39Z"
        name: posthooks1
        status: waiting
    project: defaultproject
