apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: fp2-tf
  project: defaultproject
spec:
  agents:
  - name: kalyan-docker
  fleet:
    kind: clusters
    labels:
      role: qa
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        controlPlaneUpgradeConfig:
          version: 1.24.10
        description: upgrading control plane
        name: action1
        type: controlPlaneUpgrade
      name: op1
      prehooks:
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner: cluster
        description: list all pods 10
        inject:
        - KUBECONFIG
        name: prehooks1
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner: cluster
        description: list all pods 2
        inject:
        - KUBECONFIG
        name: prehooks2
    - action:
        description: upgrading control plane and nodegroup
        name: action2
        nodeGroupsUpgradeConfig:
          names:
          - ng1
          - ng2
          version: 1.24.10
        type: nodeGroupsUpgrade
      name: op2
      posthooks:
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner: cluster
        description: list all pods 1
        inject:
        - KUBECONFIG
        name: posthooks1
status:
  jobStatus:
    lastUpdated: "2023-07-28T03:24:37Z"
    status: pending
