apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: aks-fp1
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      rafay.dev/clusterName: aks-cluster1
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        description: Upgrading ng to 1.25.11 1122
        name: ng-upgrade
        nodeGroupsUpgradeConfig:
          names:
          - primar
          version: 1.25.11
        type: nodeGroupsUpgrade
      name: op1
      prehooks:
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner:
            type: cluster
        inject:
        - KUBECONFIG
        name: hook1
