apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: eg-10
  project: defaultproject
spec:
  fleet:
    kind: clusters
    projects:
    - name: defaultproject
    - name: kalyanfleetproj4
