apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: fp1-new
  project: defaultproject
spec:
  agents:
  - name: kalyan-docker
  fleet:
    kind: clusters
    labels:
      role1: qa1
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        controlPlaneUpgradeConfig:
          version: 1.24.10
        description: upgrading control plane
        name: action1
        type: controlPlaneUpgrade
      name: op1
      prehooks:
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner:
            type: cluster
        description: list all pods 101
        inject:
        - KUBECONFIG
        name: prehooks1
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner:
            type: cluster
        description: list all pods 2
        inject:
        - KUBECONFIG
        name: prehooks2
    - action:
        description: upgrading control plane and nodegroup
        name: action2
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[0].maxSize
          value: 18
        - op: replace
          path: .spec.blueprintConfig.name
          value: minimal
        type: patch
      name: op2
      posthooks:
      - containerConfig:
          arguments:
          - get
          - po
          - -A
          image: bitnami/kubectl
          runner:
            type: cluster
        description: list all pods 1
        inject:
        - KUBECONFIG
        name: posthooks1
    - action:
        description: upgrading nodegroup
        name: action3
        nodeGroupsUpgradeConfig:
          names:
          - ng1
          - ng2
          version: 1.24.10
        type: nodeGroupsUpgrade
      name: op3
