apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: fp1
  project: defaultproject
spec:
  agents:
  - name: for-sync1
  fleet:
    kind: clusters
    labels:
      non: existent
    projects:
    - name: defaultproject
  operationWorkflow:
    operations:
    - action:
        description: upgrading nodegroup
        name: action3
        nodeGroupsUpgradeConfig:
          names:
          - ng1
          - ng2
          version: 1.24.10
        type: nodeGroupsUpgrade
      name: op3
    - action:
        description: 2r
        name: ss1r
        patchConfig:
        - op: replace
          path: threer
          value: 4r
        type: patch
      name: ref
