apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: tf-setmax-cdagent
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      op: setmax
    projects:
    - name: kalyanfleetproj4
  operationWorkflow:
    operations:
    - action:
        controlPlaneUpgradeConfig: {}
        description: set max node count
        name: setmaxnode
        nodeGroupsAndControlPlaneUpgradeConfig: {}
        nodeGroupsUpgradeConfig: {}
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[0].maxSize
          value: 55
        type: patch
      name: setmaxnode-operation
      prehooks:
      - containerConfig:
          arguments:
          - get
          - nodes
          - -A
          image: bitnami/kubectl
          runner: agent
        description: list all pods action1
        httpConfig: {}
        inject:
        - KUBECONFIG
        name: action1-prehook1
    - action:
        controlPlaneUpgradeConfig: {}
        description: scale node group
        name: setdesiredcapacity
        nodeGroupsAndControlPlaneUpgradeConfig: {}
        nodeGroupsUpgradeConfig: {}
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[0].maxSize
          value: 66
        type: patch
      name: scale-operation
      posthooks:
      - containerConfig:
          arguments:
          - get
          - pods
          - -A
          image: bitnami/kubectl
          runner: agent
        description: get pods action2
        httpConfig: {}
        inject:
        - KUBECONFIG
        name: action2-posthook1
