apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: tf-setmax-cdagent
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      op: setmax
    projects:
    - name: kalyanfleetproj4
  operationWorkflow:
    operations:
    - action:
        controlPlaneUpgradeConfig: {}
        description: set max node count
        name: setmaxnode
        nodeGroupsAndControlPlaneUpgradeConfig: {}
        nodeGroupsUpgradeConfig: {}
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[0].maxSize
          value: 55
        type: patch
      name: setmaxnode-operation
      prehooks:
      - containerConfig:
          arguments:
          - get
          - nodes
          - -A
          image: bitnami/kubectl
          runner: {}
        description: list all pods action1
        httpConfig: {}
        inject:
        - KUBECONFIG
        name: action1-prehook1
    - action:
        controlPlaneUpgradeConfig: {}
        description: scale node group
        name: setdesiredcapacity
        nodeGroupsAndControlPlaneUpgradeConfig: {}
        nodeGroupsUpgradeConfig: {}
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[0].maxSize
          value: 66
        type: patch
      name: scale-operation
      posthooks:
      - containerConfig:
          arguments:
          - get
          - pods
          - -A
          image: bitnami/kubectl
          runner: {}
        description: get pods action2
        httpConfig: {}
        inject:
        - KUBECONFIG
        name: action2-posthook1
status:
  jobStatus:
    lastUpdated: "2023-07-18T13:47:57Z"
    reason: 'activity failed: kalyanfleetproj4-kalyan-tf-eks2-action1-prehook1: timeout
      waiting for agent to ack'
    status: completed_with_failures
  resourcesStatus:
  - name: kalyan-tf-eks2
    operations:
    - action:
        description: set max node count
        lastUpdated: "2023-07-18T13:47:57Z"
        name: setmaxnode
        status: waiting
      prehooks:
      - description: list all pods action1
        lastUpdated: "2023-07-18T13:47:57Z"
        name: action1-prehook1
        reason: timeout waiting for agent to ack
        status: fail
    - action:
        description: scale node group
        lastUpdated: "2023-07-18T13:47:57Z"
        name: setdesiredcapacity
        status: waiting
      posthooks:
      - description: get pods action2
        lastUpdated: "2023-07-18T13:47:57Z"
        name: action2-posthook1
        status: waiting
    project: kalyanfleetproj4
