apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: kalyan-kubenet-kubeconfig
  project: kalyan-fleetpro2
spec:
  agents:
  - name: may12-cdagent
  fleet:
    kind: clusters
    labels:
      org: rafay
      team: qa
    projects:
    - name: kalyan-fleetpro2
    - name: kalyanfleetproj4
    - name: kalyan-fleetpro
    - name: kalyan-fleet-proj3
  operationWorkflow:
    operations:
    - action:
        name: set max nodecount
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[0].maxSize
          value: 99
        type: patch
      name: operation on target cluster
      prehooks:
      - containerConfig:
          arguments:
          - -o
          - json
          - -e
          commands:
          - /app/kubent
          image: ghcr.io/doitintl/kube-no-trouble:latest
        inject:
        - KUBECONFIG
        name: execute kubent
status:
  jobStatus:
    lastUpdated: "2023-05-12T08:20:38Z"
    reason: |-
      3 problems:

      - activity failed: kalyan-fleetpro-kalyan-fleet001-execute kubent: error initializing k8s manager for activity id 01H07GQ3381QHM56KDW272QG5Z name kalyan-fleetpro-kalyan-fleet001-execute kubent: error creating secret run-envs-01h07gq3381qhm56kdw272qg5z for run-d50539e8b59475cd-01h07gq3381qhm56kdw272qg5z: admission webhook "rafay.drift.validate" denied the request: action cannot be performed because it is a system protected resource
      - activity failed: kalyanfleetproj4-kalyan-fleet4-execute kubent: error initializing k8s manager for activity id 01H07GQ3381QHM56KDW8JAK7RX name kalyanfleetproj4-kalyan-fleet4-execute kubent: error creating secret run-envs-01h07gq3381qhm56kdw8jak7rx for run-cecece412143401b-01h07gq3381qhm56kdw8jak7rx: admission webhook "rafay.drift.validate" denied the request: action cannot be performed because it is a system protected resource
      - activity failed: kalyan-fleetpro-kalyan-multifleet-execute kubent: error initializing k8s manager for activity id 01H07GQ3381QHM56KDWBYJ0Q9T name kalyan-fleetpro-kalyan-multifleet-execute kubent: error creating secret run-envs-01h07gq3381qhm56kdwbyj0q9t for run-641636445ff9f6e0-01h07gq3381qhm56kdwbyj0q9t: admission webhook "rafay.drift.validate" denied the request: action cannot be performed because it is a system protected resource
    status: completed
  resourcesStatus:
  - name: kalyan-fleet4
    operations:
    - action:
        lastUpdated: "2023-05-12T08:20:38Z"
        name: set max nodecount
        status: waiting
      prehooks:
      - lastUpdated: "2023-05-12T08:20:38Z"
        name: execute kubent
        reason: 'error initializing k8s manager for activity id 01H07GQ3381QHM56KDW8JAK7RX
          name kalyanfleetproj4-kalyan-fleet4-execute kubent: error creating secret
          run-envs-01h07gq3381qhm56kdw8jak7rx for run-cecece412143401b-01h07gq3381qhm56kdw8jak7rx:
          admission webhook "rafay.drift.validate" denied the request: action cannot
          be performed because it is a system protected resource'
        status: fail
    project: kalyanfleetproj4
  - name: kalyan-fleet001
    operations:
    - action:
        lastUpdated: "2023-05-12T08:20:38Z"
        name: set max nodecount
        status: waiting
      prehooks:
      - lastUpdated: "2023-05-12T08:20:38Z"
        name: execute kubent
        reason: 'error initializing k8s manager for activity id 01H07GQ3381QHM56KDW272QG5Z
          name kalyan-fleetpro-kalyan-fleet001-execute kubent: error creating secret
          run-envs-01h07gq3381qhm56kdw272qg5z for run-d50539e8b59475cd-01h07gq3381qhm56kdw272qg5z:
          admission webhook "rafay.drift.validate" denied the request: action cannot
          be performed because it is a system protected resource'
        status: fail
    - action:
        lastUpdated: "2023-05-12T08:20:38Z"
        name: set max nodecount
        status: waiting
      prehooks:
      - lastUpdated: "2023-05-12T08:20:38Z"
        name: execute kubent
        reason: 'error initializing k8s manager for activity id 01H07GQ3381QHM56KDWBYJ0Q9T
          name kalyan-fleetpro-kalyan-multifleet-execute kubent: error creating secret
          run-envs-01h07gq3381qhm56kdwbyj0q9t for run-641636445ff9f6e0-01h07gq3381qhm56kdwbyj0q9t:
          admission webhook "rafay.drift.validate" denied the request: action cannot
          be performed because it is a system protected resource'
        status: fail
    project: kalyan-fleetpro
