apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: kalyan-multiprehooks
  project: kalyan-fleetpro2
spec:
  agents:
  - name: kalyan-cdagent-may11
  fleet:
    kind: clusters
    labels:
      org: rafay
      team: qa
    projects:
    - name: kalyan-fleetpro2
    - name: kalyan-fleetpro
    - name: kalyanfleetproj4
    - name: kalyan-fleet-proj3
  operationWorkflow:
    operations:
    - action:
        name: set max node managed2
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[1].maxSize
          value: 22
        type: patch
      name: set max mang2
      prehooks:
      - containerConfig:
          commands:
          - test
          - -f
          - /rafay/test/test.txt
          image: registry.dev.rafay-edge.net/rafay/prehookcheck:v1
        name: op2-prehook-1
    - action:
        name: set max mang1
        patchConfig:
        - op: replace
          path: .spec.config.managedNodeGroups[0].maxSize
          value: 11
        type: patch
      name: setmax for managed0
      prehooks:
      - containerConfig:
          commands:
          - test
          - -f
          - /rafay/test/test.txt
          image: registry.dev.rafay-edge.net/rafay/prehookcheck:v1
        name: prehook-1
      - containerConfig:
          commands:
          - test
          - -f
          - /rafay/test/test.txt
          image: registry.dev.rafay-edge.net/rafay/prehookcheck:v1
        name: prehook-2
      - containerConfig:
          commands:
          - test
          - -f
          - /rafay/test/test.txt
          image: registry.dev.rafay-edge.net/rafay/prehookcheck:v1
        name: prehook-3
      - containerConfig:
          commands:
          - test
          - -f
          - /rafay/test/test.txt
          image: registry.dev.rafay-edge.net/rafay/prehookcheck:v1
        name: prehook-4
status:
  jobStatus:
    lastUpdated: "2023-05-11T11:22:37Z"
    reason: all activities completed
    status: completed
  resourcesStatus:
  - name: kalyan-ekscls2
    operations:
    - action:
        lastUpdated: "2023-05-11T11:22:37Z"
        name: set max mang1
        reason: 'activity poll again: kalyan-fleetpro2-kalyan-ekscls2-set max mang1'
        status: success
      prehooks:
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-1
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-2
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-3
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-4
        status: success
    - action:
        lastUpdated: "2023-05-11T11:22:37Z"
        name: set max node managed2
        reason: 'activity poll again: kalyan-fleetpro2-kalyan-ekscls2-set max node
          managed2'
        status: success
      prehooks:
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: op2-prehook-1
        status: success
    project: kalyan-fleetpro2
  - name: kalyan-multifleet
    operations:
    - action:
        lastUpdated: "2023-05-11T11:22:37Z"
        name: set max mang1
        reason: 'activity poll again: kalyan-fleetpro-kalyan-multifleet-set max mang1'
        status: success
      prehooks:
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-1
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-2
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-3
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-4
        status: success
    - action:
        lastUpdated: "2023-05-11T11:22:37Z"
        name: set max node managed2
        reason: 'activity poll again: kalyan-fleetpro-kalyan-multifleet-set max node
          managed2'
        status: success
      prehooks:
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: op2-prehook-1
        status: success
    project: kalyan-fleetpro
  - name: kalyan-fleet4
    operations:
    - action:
        lastUpdated: "2023-05-11T11:22:37Z"
        name: set max mang1
        reason: 'activity poll again: kalyanfleetproj4-kalyan-fleet4-set max mang1'
        status: success
      prehooks:
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-1
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-2
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-3
        status: success
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: prehook-4
        status: success
    - action:
        lastUpdated: "2023-05-11T11:22:37Z"
        name: set max node managed2
        reason: 'activity poll again: kalyanfleetproj4-kalyan-fleet4-set max node
          managed2'
        status: success
      prehooks:
      - lastUpdated: "2023-05-11T11:22:37Z"
        name: op2-prehook-1
        status: success
    project: kalyanfleetproj4
